name: Pre-Commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Install terraform-docs
        run: |
          set -euo pipefail
          VERSION="v0.20.0"
          curl -fsSL -o /tmp/terraform-docs.tar.gz "https://github.com/terraform-docs/terraform-docs/releases/download//terraform-docs--linux-amd64.tar.gz"
          tar -xzf /tmp/terraform-docs.tar.gz -C /tmp terraform-docs
          sudo mv /tmp/terraform-docs /usr/local/bin/terraform-docs
          terraform-docs version

      - name: Install tfsec
        run: |
          set -euo pipefail
          VERSION="v1.28.14"
          curl -sSL -o /tmp/tfsec "https://github.com/aquasecurity/tfsec/releases/download/${VERSION}/tfsec-linux-amd64"
          chmod +x /tmp/tfsec
          sudo mv /tmp/tfsec /usr/local/bin/tfsec
          tfsec --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --color=always --show-diff-on-failure
